[package]
name = "crosspond_theme"
version = "0.2.1"
edition = "2024"
description = "Themes for crosspond"
license = "MIT"

[dependencies]
edtui = "0.9.6"
ratatui = { version = "0.29.0", features = ["palette"] }
